language: go
sudo: required
dist: trusty
services:
- docker
go:
- 1.11.x
script:
- env GO111MODULE=on go build -o app weather/weather.go
after_success:
- echo "$HEROKU_PASSWORD" | docker login --username="_" --password-stdin registry.heroku.com;
- docker build --no-cache -t hkweather/app .;
- docker tag hkweather/app:latest registry.heroku.com/blooming-bayou-30755/web;
- docker push registry.heroku.com/blooming-bayou-30755/web;
- >-
  curl -n -X PATCH https://api.heroku.com/apps/blooming-bayou-30755/formation
  -d '{
  "updates": [
    {
      "type": "web",
      "docker_image": "$(docker images hkweather/app --format={{.ID}})"
    }
    ]
  }' 
  -H "Content-Type: application/json" 
  -H "Accept: application/vnd.heroku+json; version=3.docker-releases"
branches:
  only:
  - master
env:
  secure: M5SjtCe31SOfepraaGgSH6XlpuCDXntu4J6w3qnzdhQaQ83ViUSdUlLj4BmaUVfNR2KiRvO+RA5uQKYlUQOCN2Hc9Ywqfbp/4Bl14NnEsV6BkgfzN1mgAo2/ocoRKJXLVgC66wLrElfWMgI+DofkSRDeCrMmvCjAZm5ZunR0ILcdKl5s3fzKsuZdN4tnXAPrPsnEzPWU62B391eg39A4w3x7YOCv+y7SJZyCXzYWOx4SiqmZS4wqT9r6sL8oCI08WXim0UT6J32iI/9j+kkoJnfp93BGZpEE4SIUU3ZaNLP1WIb3Fe5LpKvPpp/a2XDwF3KHnHHLmNsp7qcqdEBsEb17o+0DaC/zK9dgEugQRxNnz6TyT17/Rgk/Ttp+i8mSRAmYepZKEjZzCtAoKm5aYJpop7LAebuXAUj8d/CLCJJOoBPz88oG4JwO+qllSO+yZVK9BcnSHetsw5K1b5B6VsT0F+CpQDFRVCQAzPe+pawL9bA6AAmHdzx8igNtA9EeDTalGI8mL2REYW5FAmNQdUg7pZOjiTb1qVPJymXVEUd7AY9QOPRcBfj/+orjq5af629mfVy04+IxZL2SQdk/5U6g8pMbU6vQhxoADaXWJh8IzG5UMsF6hiEIw1Rh1jjPiHPSlwzGw2+EUISLzhBh4EGeF/dzCGw+EtjU/Cglypk=
