language: go
sudo: required
dist: trusty
env:
  global:
     - secure: "PVczVqnJiaOFmC4FkedRikOQTegi4sQ58EkeHj59GYDt/aXLp/ZvWe+PX0FPHsNUWt16JIfcb2YINSZUi902Cs9DBK4CwweuEGA015iKM/i92eLgKeoP2mMOkTj2O3KldBc+sUi6FmrEmIfO4yo91wcJ1VDjiq+c8ZvufkyYXnjAoNLBmZsElXwz8OG2AdqLHJR2NQFDF+VQsz2wGI2IBYVz9gHy1FUOhTHTEI27cggRgfYtscnqeJG9Vipkf1C+cq0fn9ihNC54fhTG3YZoHzY79/0qnQq9ko40S4yC5/ME3s1+PNy/NSTUV+KaxjhzcQDP5iGeXYXbYIV0IOmKyO5YqeGQhKaz7EYuxkKJSY4grrATU66ihpYLTjUX2BWg+5dgvsfmGV/XQBjTgHJvnelMV3cD0gnsqiLfqyvD4KTIcc8YYZa6ch+PICr6RLGfp2Z4UNUJMD2+Uo0FBmPjO5MO8EXBVEvYYJPaHyZel6Vhq+gQECb3zpWiYGWa1vtUgQ7l6BobnJejPxjmlI8czCRcGQcI1StTGgYK24h3iOwY3xbLXQtVJzGauM91GtHrjfSIVushmxR3Uho2RODsBYq3z6kNUCtQwNcarFSi8FmUYcRggMU+ijph2hDpNOCUL9PPwwpkrptJX6q41ANsNEKMxbLM99Ou/2JrVypi3JQ="
     - secure: "sdVtT0CwVgdrSsTo5W7mPyRpqPBizgLlaH0WxDsuD6idTc2LUv1V5c8+5J+TwKYSkbCq/9TaD1nzJf5JMC++crhCanQVg4fO/eaHC1J2SkYo90/w5j5iEDr4x5By/DU0DF9oKXxRHTMuYZGvHmbGdGQvLHwH7emg61pX6BQFpdHpiA5ji/u2iCwJoyh9eOoSmPUi+KbUuOXrhGZL6vNYugbPnpyG/UTBtE23PDz+N1C8SWKj+TVWgABRdBuO2/+sZ85PC2ovAeuzXBhh04Zvp58nX3wpY0VsgNpmO9E7qjc35KP1jZ0YHdR+jvHnOBKsguw3V+R3PPKnd1V8+pdxfgjzp86s1YE18RFuiHPYfcyH6aBhvl78XFrnIvpqV3rkte6o5IdEbLqRjYPonOKu0/y3NGjjrlZWbktdSlfiwJYrMebQdnNUn3el96Jzdbn/zcvkk+3Y1zqyys/Zky4zJNWz2MImsfmnnjJ5ZZBrz0eqnFLT3y+/8l9A9EUGzsO18dzuKyewgU71dG/LnDZWdHH87XfTiO3KOO5PoN1KPQBEHQwIxSMZv/uwJvj7rZwMonM6c7WnzLTQ4jdeAF8Efl0cfso2MJEpYQh0zvTzdqb2Iaa6eIwPvPtnMmWxtA9+6nZh761ZD+8Ad6Yh7rVT1T7owGUp6N9kcm88FCBODtk="

services:
  - docker
go:
  - "1.11.x"

install:true

script:
  - env GO111MODULE=on go build -o app hkweather/weather.go
after_success:
 - docker login -u="$HEROKU_USERNAME" -p="$HEROKU_PASSWORD" registry.heroku.com;
 - docker build --no-cache -t hkweather/app;
 - docker tag hkweather/app:latest registry.heroku.com/blooming-bayou-30755/web;
 - docker push hkweather/app:latest;

branches:
  only:
     - master

